# Generated by Django 5.2.8 on 2025-12-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home_hero', 'Home - Hero Banner'), ('home_deals', 'Home - Ofertas'), ('home_categories', 'Home - Categorías'), ('product_banner', 'Producto - Banner'), ('category_banner', 'Categoría - Banner'), ('checkout_promo', 'Checkout - Promoción'), ('blog_featured', 'Blog - Destacado'), ('seasonal', 'Campaña Temporal'), ('footer_promo', 'Footer - Promoción'), ('custom', 'Personalizado')], db_index=True, default='home_hero', help_text='Sección donde se mostrará este slider', max_length=50, verbose_name='Sección')),
                ('title', models.CharField(help_text='Solo para admin, no se muestra en frontend', max_length=200, verbose_name='Título interno')),
                ('content', models.JSONField(default=dict, help_text='Estructura JSON con todo el contenido del slider', verbose_name='Contenido')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('start_date', models.DateTimeField(blank=True, help_text='Opcional: fecha desde cuando estará activo', null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, help_text='Opcional: fecha hasta cuando estará activo', null=True, verbose_name='Fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['section', 'order', '-created_at'],
                'indexes': [models.Index(fields=['section', 'is_active', 'order'], name='configurati_section_9c6408_idx')],
            },
        ),
    ]
