# Generated by Django 5.2.8 on 2025-12-16 06:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(default=1, help_text='Formatos: JPG, PNG, WEBP, GIF. Máx 5MB', upload_to='sliders/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='content',
            field=models.JSONField(default=dict, help_text='Estructura JSON con contenido adicional', verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(help_text='Solo para admin', max_length=200, verbose_name='Título interno'),
        ),
    ]
