# Generated by Django 5.2.8 on 2025-12-16 06:43

import django.core.validators
import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_slider_image_alter_slider_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='Formatos: JPG, PNG, WEBP, GIF. Máx 5MB', upload_to='sliders/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Imagen'),
        ),
    ]
