# Generated by Django 5.2.8 on 2025-12-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_slider_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='slug',
            field=models.SlugField(default='dela', help_text='URL amigable (se genera automáticamente si está vacío)', max_length=200, unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='slider',
            index=models.Index(fields=['slug'], name='configurati_slug_790fe3_idx'),
        ),
    ]
