# Generated by Django 5.2.8 on 2025-12-29 02:13

import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('configuration', '0004_slider_slug_slider_configurati_slug_790fe3_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la página (se muestra en el navegador y H1)', max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='URL amigable (se genera automáticamente)', max_length=200, unique=True, verbose_name='Slug')),
                ('page_type', models.CharField(choices=[('legal', 'Legal'), ('about', 'Institucional'), ('help', 'Ayuda/Soporte'), ('policy', 'Políticas'), ('custom', 'Personalizada')], db_index=True, default='custom', help_text='Categoría de la página', max_length=20, verbose_name='Tipo de Página')),
                ('template', models.CharField(choices=[('default', 'Plantilla por Defecto'), ('full_width', 'Ancho Completo'), ('sidebar', 'Con Sidebar'), ('landing', 'Landing Page'), ('contact', 'Contacto')], default='default', help_text='Plantilla de diseño a usar', max_length=20, verbose_name='Plantilla')),
                ('content', tinymce.models.HTMLField(help_text='Contenido principal de la página (HTML con TinyMCE)', verbose_name='Contenido')),
                ('excerpt', models.TextField(blank=True, help_text='Resumen corto para meta description y previews', max_length=500, null=True, verbose_name='Extracto')),
                ('featured_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Imagen principal de la página', null=True, upload_to='pages/%Y/%m/', verbose_name='Imagen Destacada')),
                ('meta_title', models.CharField(blank=True, help_text='Título para SEO (máx 70 caracteres). Si vacío, usa el título principal', max_length=70, null=True, verbose_name='Meta Título')),
                ('meta_description', models.CharField(blank=True, help_text='Descripción para SEO (máx 160 caracteres). Si vacío, usa el extracto', max_length=160, null=True, verbose_name='Meta Descripción')),
                ('meta_keywords', models.CharField(blank=True, help_text='Palabras clave separadas por comas', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Mostrar/ocultar página', verbose_name='Publicado')),
                ('show_in_menu', models.BooleanField(default=False, help_text='Sugerir esta página para menús automáticos', verbose_name='Mostrar en Menú')),
                ('require_auth', models.BooleanField(default=False, help_text='Solo usuarios logueados pueden ver esta página', verbose_name='Requiere Autenticación')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización en listados', verbose_name='Orden')),
                ('published_at', models.DateTimeField(blank=True, help_text='Programar publicación', null=True, verbose_name='Fecha de Publicación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['page_type', 'order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='configurati_slug_84c9e3_idx'), models.Index(fields=['page_type', 'is_published'], name='configurati_page_ty_44e908_idx'), models.Index(fields=['is_published', 'published_at'], name='configurati_is_publ_0f262b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Texto que se mostrará en el menú', max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(help_text='Se genera automáticamente del nombre', max_length=100, unique=True, verbose_name='Slug')),
                ('menu_type', models.CharField(choices=[('header', 'Menú Principal (Header)'), ('footer', 'Menú Footer'), ('mobile', 'Menú Móvil'), ('sidebar', 'Menú Lateral'), ('custom', 'Personalizado')], db_index=True, default='header', help_text='Ubicación donde se mostrará este menú', max_length=20, verbose_name='Tipo de Menú')),
                ('link_type', models.CharField(choices=[('url', 'URL Personalizada'), ('category', 'Categoría'), ('page', 'Página'), ('external', 'Enlace Externo'), ('megamenu', 'Mega Menú')], default='url', help_text='Tipo de contenido que enlaza este menú', max_length=20, verbose_name='Tipo de Enlace')),
                ('url', models.CharField(blank=True, help_text='URL personalizada (ej: /shop, /about, https://external.com)', max_length=500, null=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, help_text='Clase de icono (ej: fa-home, bi-cart, lucide-menu)', max_length=100, null=True, verbose_name='Icono')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Imagen opcional para mega menús', null=True, upload_to='menus/%Y/%m/', verbose_name='Imagen')),
                ('description', models.TextField(blank=True, help_text='Descripción que aparece al hacer hover o en mega menús', max_length=500, null=True, verbose_name='Descripción')),
                ('css_classes', models.CharField(blank=True, help_text='Clases CSS separadas por espacios (ej: btn-primary highlight featured)', max_length=255, null=True, verbose_name='Clases CSS')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Atributos HTML personalizados en formato JSON', verbose_name='Atributos HTML')),
                ('order', models.IntegerField(default=0, help_text='Orden de visualización (menor número = primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Mostrar/ocultar este item del menú', verbose_name='Activo')),
                ('open_in_new_tab', models.BooleanField(default=False, help_text="Agregar target='_blank' al enlace", verbose_name='Abrir en nueva pestaña')),
                ('is_featured', models.BooleanField(default=False, help_text='Marcar como destacado (para estilos especiales)', verbose_name='Destacado')),
                ('mega_menu_columns', models.IntegerField(default=1, help_text='Número de columnas si es mega menú (1-6)', verbose_name='Columnas de Mega Menú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('category', models.ForeignKey(blank=True, help_text="Categoría a la que enlaza (solo si link_type='category')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='category.category', verbose_name='Categoría')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Dejar vacío para menú de nivel raíz', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='configuration.menu', verbose_name='Menú Padre')),
                ('page', models.ForeignKey(blank=True, help_text="Página a la que enlaza (solo si link_type='page')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='configuration.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Menú',
                'verbose_name_plural': 'Menús',
                'ordering': ['menu_type', 'tree_id', 'lft'],
                'indexes': [models.Index(fields=['menu_type', 'is_active', 'order'], name='configurati_menu_ty_f5f7c0_idx'), models.Index(fields=['slug'], name='configurati_slug_a3ea63_idx'), models.Index(fields=['link_type'], name='configurati_link_ty_9959cf_idx')],
            },
        ),
    ]
