# Generated by Django 5.2.8 on 2025-12-02 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product_base', '0002_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del descuento', max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Valor del descuento', max_digits=15)),
                ('discount_type', models.CharField(choices=[('Amount', 'Monto Fijo'), ('Percentaje', 'Porcentaje')], default='Percentaje', max_length=10)),
                ('start_date', models.DateTimeField(blank=True, help_text='Inicio del descuento (opcional)', null=True)),
                ('expiration_date', models.DateTimeField(blank=True, help_text='Fin del descuento (opcional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_discounts', to='category.category')),
            ],
            options={
                'verbose_name': 'Descuento por Categoría',
                'verbose_name_plural': 'Descuentos por Categoría',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la campaña (ej: Black Friday 2024)', max_length=255)),
                ('code', models.SlugField(help_text='Código único (ej: black-friday-2024)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descripción de la campaña')),
                ('campaign_type', models.CharField(choices=[('global', 'Global - Todos los productos'), ('category', 'Por Categoría'), ('products', 'Productos Específicos')], default='global', help_text='Alcance de la campaña', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, help_text='Valor del descuento', max_digits=15)),
                ('discount_type', models.CharField(choices=[('Amount', 'Monto Fijo'), ('Percentaje', 'Porcentaje')], default='Percentaje', max_length=10)),
                ('start_date', models.DateTimeField(help_text='Inicio de la campaña')),
                ('expiration_date', models.DateTimeField(help_text='Fin de la campaña')),
                ('is_active', models.BooleanField(default=True, help_text='¿Campaña activa?')),
                ('priority', models.IntegerField(default=0, help_text='Prioridad (mayor número = mayor prioridad)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text="Categorías incluidas (solo si campaign_type='category')", related_name='discount_campaigns', to='category.category')),
                ('products', models.ManyToManyField(blank=True, help_text="Productos incluidos (solo si campaign_type='products')", related_name='discount_campaigns', to='product_base.productbase')),
            ],
            options={
                'verbose_name': 'Campaña de Descuento',
                'verbose_name_plural': 'Campañas de Descuento',
                'ordering': ['-priority', '-start_date'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'expiration_date'], name='campaing_di_is_acti_56d1bc_idx'), models.Index(fields=['-priority'], name='campaing_di_priorit_6de190_idx')],
            },
        ),
    ]
