# Generated by Django 5.1.6 on 2025-11-28 08:45

import django.db.models.deletion
import easy_thumbnails.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_base', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=255, upload_to='images/image')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Product_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_base', to='product_base.productbase')),
                ('tag', taggit.managers.TaggableManager(help_text='Tags de estilo y categoría para la venta (ej: #Económico, #Packaging).', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='TagsStyle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(max_length=255, upload_to='product/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prosuct_images', to='product_ins.product')),
            ],
        ),
    ]
