# Generated by Django 5.2.8 on 2025-12-01 17:17

import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_base', '0001_initial'),
        ('product_ins', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['created_at'], 'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de productos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(help_text='Imagen adicional del producto', max_length=255, upload_to='images/products/gallery'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='product_ins.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_base',
            field=models.ForeignKey(help_text='Producto base del cual deriva esta instancia', on_delete=django.db.models.deletion.CASCADE, related_name='product_instances', to='product_base.productbase'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del producto personalizado', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Imagen principal del producto', max_length=255, upload_to='images/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(blank=True, db_index=True, help_text='Código único del producto', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='published',
            field=models.BooleanField(db_index=True, default=True, help_text='Indica si el producto está visible públicamente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags de estilo y categoría (ej: #Económico, #Packaging)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(help_text='Usuario creador del producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at', 'published'], name='product_ins_created_20ac2c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user', 'published'], name='product_ins_user_id_87f982_idx'),
        ),
    ]
