# Generated by Django 5.1.6 on 2025-11-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tokenblacklist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenblacklist',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tokenblacklist',
            name='token_black_user_id_f131e0_idx',
        ),
        migrations.RemoveField(
            model_name='tokenblacklist',
            name='blacklisted_at',
        ),
        migrations.AlterField(
            model_name='tokenblacklist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='tokenblacklist',
            table=None,
        ),
    ]
