# Generated by Django 5.1.6 on 2025-11-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_tokenblacklist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
