# Generated by Django 5.2.8 on 2025-12-09 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccount_last_password_reset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del permiso (ej: product.create)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(help_text='Módulo al que pertenece (ej: product, user, order)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'ordering': ['module', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='URL donde enviar los eventos')),
                ('events', models.JSONField(default=list, help_text='Lista de eventos que debe escuchar')),
                ('secret', models.CharField(help_text='Secret para firmar los webhooks', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Headers adicionales para enviar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del rol (ej: Admin, Moderator, Designer)', max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='Roles del sistema no se pueden eliminar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='user.permission')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='useraccount',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Roles asignados al usuario', related_name='users', to='user.role'),
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('secret_key', models.CharField(help_text='Secret key para TOTP', max_length=32)),
                ('backup_codes', models.JSONField(default=list, help_text='Códigos de respaldo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autenticación de Dos Factores',
                'verbose_name_plural': 'Autenticaciones de Dos Factores',
            },
        ),
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('register', 'Register'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change'), ('email_verify', 'Email Verify'), ('token_refresh', 'Token Refresh'), ('2fa_verify', '2FA Verify'), ('2fa_failed', '2FA Failed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Autenticación',
                'verbose_name_plural': 'Logs de Autenticación',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='user_authlo_user_id_817566_idx'), models.Index(fields=['event_type', '-timestamp'], name='user_authlo_event_t_608e26_idx'), models.Index(fields=['ip_address', '-timestamp'], name='user_authlo_ip_addr_29d494_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('response_status', models.IntegerField(null=True)),
                ('response_body', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=1)),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='user.webhook')),
            ],
            options={
                'verbose_name': 'Log de Webhook',
                'verbose_name_plural': 'Logs de Webhooks',
                'ordering': ['-delivered_at'],
                'indexes': [models.Index(fields=['webhook', '-delivered_at'], name='user_webhoo_webhook_73ff46_idx'), models.Index(fields=['event_type', '-delivered_at'], name='user_webhoo_event_t_f73df2_idx')],
            },
        ),
    ]
