# Generated by Django 5.1.6 on 2025-11-28 08:45

import django.db.models.deletion
import easy_thumbnails.fields
import taggit.managers
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('short_description', models.TextField(blank=True, max_length=500, null=True)),
                ('description', tinymce.models.HTMLField()),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, max_length=255, upload_to='images/image')),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product_base', to='category.category')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='Tags de estilo y categoría para la venta (ej: #Económico, #Packaging).', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='TagsStyle')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(choices=[('Unidad', 'unidad'), ('Docena', 'docena')], max_length=225)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percentaje', 'Percentaje')], default='Amount', max_length=10, null=True)),
                ('quantity', models.IntegerField()),
                ('time_production', models.IntegerField(default=1, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_base_prices', to='product_base.productbase')),
            ],
            options={
                'verbose_name': 'price',
                'verbose_name_plural': 'prices',
            },
        ),
        migrations.CreateModel(
            name='ImageProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(max_length=255, upload_to='product/images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_base_images', to='product_base.productbase')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percentaje', 'Percentaje')], default='Amount', max_length=10, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_base_discounts', to='product_base.productbase')),
            ],
            options={
                'verbose_name': 'discount',
                'verbose_name_plural': 'discounts',
            },
        ),
    ]
