# Generated by Django 5.2.8 on 2025-12-02 06:32

import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import taggit.managers
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product_base', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-start_date'], 'verbose_name': 'Descuento', 'verbose_name_plural': 'Descuentos'},
        ),
        migrations.AlterModelOptions(
            name='imageproductbase',
            options={'ordering': ['created_at'], 'verbose_name': 'Imagen de producto base', 'verbose_name_plural': 'Imágenes de productos base'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['quantity'], 'verbose_name': 'Precio', 'verbose_name_plural': 'Precios'},
        ),
        migrations.AlterModelOptions(
            name='productbase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Producto Base', 'verbose_name_plural': 'Productos Base'},
        ),
        migrations.AddField(
            model_name='imageproductbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor del descuento', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Amount', 'Monto Fijo'), ('Percentaje', 'Porcentaje')], default='Amount', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_date',
            field=models.DateTimeField(blank=True, help_text='Fin de la promoción', null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Inicio de la promoción', null=True),
        ),
        migrations.AlterField(
            model_name='imageproductbase',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=255, upload_to='images/product-base/gallery'),
        ),
        migrations.AlterField(
            model_name='price',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Descuento aplicable a este precio específico', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Amount', 'Monto Fijo'), ('Percentaje', 'Porcentaje')], default='Amount', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Precio base por unidad/docena', max_digits=15),
        ),
        migrations.AlterField(
            model_name='price',
            name='quantity',
            field=models.IntegerField(help_text='Cantidad mínima para este precio'),
        ),
        migrations.AlterField(
            model_name='price',
            name='time_production',
            field=models.IntegerField(default=1, help_text='Días de producción estimados', null=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='unit',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Docena', 'Docena')], help_text='Unidad de medida', max_length=225),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='category',
            field=models.ForeignKey(help_text='Categoría del producto', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='description',
            field=tinymce.models.HTMLField(help_text='Descripción completa con formato HTML'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Imagen principal del producto', max_length=255, upload_to='images/product-base'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='key',
            field=models.CharField(blank=True, db_index=True, help_text='Código único del producto base', max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='published',
            field=models.BooleanField(db_index=True, default=True, help_text='¿Visible para los usuarios?'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='short_description',
            field=models.TextField(blank=True, help_text='Descripción breve para listados', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='slug',
            field=models.SlugField(help_text='URL amigable (ej: tarjetas-de-presentacion)', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='Tags de estilo y categoría (ej: #Económico, #Packaging)', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='title',
            field=models.CharField(help_text='Nombre del producto (ej: Tarjetas de Presentación)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='discount',
            index=models.Index(fields=['product', 'start_date', 'expiration_date'], name='product_bas_product_2d29fd_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['product', 'quantity'], name='product_bas_product_f7afe1_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['-created_at', 'published'], name='product_bas_created_2161c5_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['slug'], name='product_bas_slug_317f6c_idx'),
        ),
        migrations.AddIndex(
            model_name='productbase',
            index=models.Index(fields=['category', 'published'], name='product_bas_categor_e223f1_idx'),
        ),
    ]
