# Generated by Django 5.2.8 on 2025-12-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_base', '0002_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='unit',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Docena', 'Docena'), ('Caja', 'Caja'), ('Paquete', 'Paquete'), ('Kilogramo', 'Kilogramo'), ('Metro', 'Metro'), ('Litro', 'Litro')], help_text='Unidad de medida', max_length=225),
        ),
    ]
